apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gsapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem

